name: Run checks
on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
      - stg
      - dev

jobs:
  typecheck:
    name: ʦ TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: 🔎 Type check
        run: npm run typecheck --if-present

  lint:
    name: Run linters
    runs-on: [self-hosted, linux, X64]

    steps:
      - uses: AutoModality/action-clean@v1
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install modules
        run: npm install

      - name: Lint Code
        run: npm run lint

      - uses: AutoModality/action-clean@v1

  run-build:
    runs-on: [self-hosted, linux, X64]
    steps:
      - name: ⬇️ Checkout repo
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: 📥 Download deps
      - run: npm install

      - run: CI=false npm run build

      - name: 🔎 Build
        run: npm run build

      - name: Cleaning workspace
        uses: AutoModality/action-clean@v1
        if: ${{ always() }}
